name: Unit and Functional Testing

on:
  push:
    branches: [ "4.x" ]
  pull_request:
    branches: [ "4.x" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        typo3: [ 9.5, 10.4 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: Build/Test/runTests.sh -s composerInstall -t ${{ matrix.typo3 }}

      - name: Run unit tests
        run: Build/Test/runTests.sh -s unit

      - name: Run functional tests
        run: Build/Test/runTests.sh -s functional
